In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [3]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [4]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [7]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [8]:
data.replace([-999, -1000], [np.nan, 420])

0      1.0
1      NaN
2      2.0
3      NaN
4    420.0
5      3.0
dtype: float64

In [10]:
data.replace({-999: np.nan, -1000: 999})

0      1.0
1      NaN
2      2.0
3      NaN
4    999.0
5      3.0
dtype: float64

In [17]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=["Ohio", "Colorado", "New York"],
                   columns=["one", "two", "three", "four"])

In [18]:
def transform(x):
    return x[:4].upper()

In [19]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [20]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [21]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [22]:
data.rename(index={"OHIO": "INDIANA"},
           columns={"three": "peekaboo"})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [23]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [24]:
bins = [18, 25, 35, 60, 100]

In [25]:
age_categories = pd.cut(ages, bins)

In [26]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [27]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [28]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [29]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [30]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [31]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [32]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [33]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [34]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [35]:
data = np.random.uniform(size=20)

In [36]:
pd.cut(data, 4, precision=2)

[(0.0028, 0.24], (0.24, 0.48], (0.0028, 0.24], (0.48, 0.72], (0.0028, 0.24], ..., (0.48, 0.72], (0.0028, 0.24], (0.72, 0.95], (0.72, 0.95], (0.24, 0.48]]
Length: 20
Categories (4, interval[float64, right]): [(0.0028, 0.24] < (0.24, 0.48] < (0.48, 0.72] < (0.72, 0.95]]

In [37]:
data = np.random.standard_normal(1000)

In [38]:
quartiles = pd.qcut(data, 4, precision=2)

In [39]:
quartiles

[(-3.51, -0.73], (0.69, 3.17], (-3.51, -0.73], (0.69, 3.17], (-0.73, -0.013], ..., (-3.51, -0.73], (-0.013, 0.69], (0.69, 3.17], (0.69, 3.17], (-0.73, -0.013]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.51, -0.73] < (-0.73, -0.013] < (-0.013, 0.69] < (0.69, 3.17]]

In [40]:
pd.value_counts(quartiles)

(-3.51, -0.73]     250
(-0.73, -0.013]    250
(-0.013, 0.69]     250
(0.69, 3.17]       250
dtype: int64

In [41]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.497, -1.335]     100
(-1.335, -0.0127]    400
(-0.0127, 1.238]     400
(1.238, 3.174]       100
dtype: int64

In [42]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [43]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.014878     0.022752    -0.013205     0.011841
std       0.997308     0.986683     0.986692     1.021373
min      -3.139761    -3.126564    -3.506777    -3.217069
25%      -0.647120    -0.631907    -0.664388    -0.684398
50%      -0.010780     0.021044     0.002242     0.006780
75%       0.591974     0.667728     0.691835     0.710677
max       3.836029     3.224105     3.913125     3.366714

In [44]:
col = data[2]

In [45]:
col[col.abs() > 3]

485    3.913125
617   -3.506777
Name: 2, dtype: float64

In [46]:
col = data[2]

In [47]:
col[col.abs() > 3]

485    3.913125
617   -3.506777
Name: 2, dtype: float64

In [48]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
54  -1.474805 -1.181391 -0.005600  3.125579
98  -0.752593 -3.091688  0.154208 -0.172933
131 -2.108933 -0.545968  1.445085  3.366714
266  3.210453  1.708399  0.378023  0.137880
302 -0.251610 -0.832259 -0.848310 -3.217069
352 -3.139761 -0.579034  0.223750  0.488932
395  0.098304  3.224105  0.085028  1.449590
485  1.717366  0.082938  3.913125 -0.130738
524  0.786112 -3.120393  1.540371 -0.715175
617  0.263351  0.110793 -3.506777  0.665737
871  3.284898 -0.349216 -0.299286 -2.383030
917  3.836029  0.683188 -0.776098  0.032947
963  0.243751 -3.126564 -0.453433  0.089474
977  3.418141  2.258539 -0.045092  0.386859

In [49]:
data[data.abs() > 3] = np.sign(data) * 3

In [50]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013268     0.022866    -0.013612     0.011566
std       0.991111     0.984921     0.981799     1.019192
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.647120    -0.631907    -0.664388    -0.684398
50%      -0.010780     0.021044     0.002242     0.006780
75%       0.591974     0.667728     0.691835     0.710677
max       3.000000     3.000000     3.000000     3.000000

In [51]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0 -1.0  1.0  1.0
2  1.0  1.0  1.0 -1.0
3  1.0  1.0  1.0  1.0
4  1.0 -1.0  1.0  1.0

In [52]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [53]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [54]:
sampler = np.random.permutation(5)

In [55]:
sampler

array([3, 0, 2, 1, 4])

In [56]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [57]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [58]:
column_sampler = np.random.permutation(7)

In [60]:
column_sampler

array([3, 1, 0, 2, 4, 5, 6])

In [61]:
df.take(column_sampler, axis="columns")

3   1   0   2   4   5   6
0   3   1   0   2   4   5   6
1  10   8   7   9  11  12  13
2  17  15  14  16  18  19  20
3  24  22  21  23  25  26  27
4  31  29  28  30  32  33  34

In [62]:
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [63]:
choices = pd.Series([5, 7, -1, 6, 4])

In [64]:
choices.sample(n=10, replace=True)

4    4
0    5
1    7
4    4
2   -1
3    6
3    6
3    6
0    5
2   -1
dtype: int64

In [65]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                  "data1": range(6)})

In [66]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [67]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [68]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [69]:
df_with_dummy = df[["data1"]].join(dummies)

In [70]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0