In [5]:
import numpy as np

In [6]:
my_arr = np.arange(1_000_000)

In [7]:
my_list = list(range(1_000_000))

In [8]:
%timeit my_arr2 = my_arr * 2

736 µs ± 63.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%timeit my_list2 = [x * 2 for x in my_list]

32.7 ms ± 707 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
import numpy as np

In [12]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [13]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [14]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [15]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data1 = [6, 7.5, 8, 0, 1]

In [19]:
arr1 = np.array(data1)

In [21]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
arr2 = np.array(data2)

In [25]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 4)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int64')

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.empty((2, 3, 2))

array([[[-1.49166815e-154,  2.68156179e+154],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  7.24776997e-309],
        [ 2.72377097e-314,  8.34406941e-309]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [35]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr

array([1., 2., 3., 4., 5.])

In [42]:
float_arr.dtype

dtype('float64')

In [43]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12,9, 10.1])

In [44]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12. ,  9. , 10.1])

In [45]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12,  9, 10], dtype=int32)

In [47]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [48]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [52]:
int_array = np.arange(10)

In [53]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [54]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [56]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [57]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [58]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [60]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [63]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [64]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [65]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [66]:
arr = np.arange(10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

5

In [69]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr[5:8] = 12

In [71]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [72]:
arr_slice = arr[5:8]

In [73]:
arr_slice

array([12, 12, 12])

In [74]:
arr_slice[1] = 12345

In [75]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [76]:
arr_slice[:] = 64

In [77]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [78]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [79]:
arr2d[2]

array([7, 8, 9])

In [80]:
arr2d[0][2]

3

In [81]:
arr2d[0, 2]

3

In [82]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
old_values = arr3d[0].copy()

In [86]:
arr3d[0] = 42

In [87]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[1, 0]

array([7, 8, 9])

In [91]:
x = arr3d[1]

In [92]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [93]:
x[0]

array([7, 8, 9])

In [94]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [95]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [96]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [99]:
lower_dim_slice = arr2d[1, :2]

In [100]:
lower_dim_slice.shape

(2,)

In [101]:
arr2d[:2, 2]

array([3, 6])

In [102]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [103]:
arr2d[:2, 1:] = 0

In [104]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [105]:
names = np.array(["Bob", "Joe", "Bob", "Will", "Joe", "Joe"])

In [107]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [108]:
names

array(['Bob', 'Joe', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [109]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [110]:
names == "Bob"

array([ True, False,  True, False, False, False])

In [113]:
names != "Bob"

array([False,  True, False,  True,  True,  True])

In [114]:
(names == "Bob")

array([ True, False,  True, False, False, False])

In [116]:
cond = names == "Bob"

In [118]:
mask = (names == "Bob") | (names == "Will")

In [119]:
mask

array([ True, False,  True,  True, False, False])

data[mask]

In [121]:
data[data < 0] = 0

In [122]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [124]:
arr = np.zeros((8, 4))

In [125]:
for i in range(8):
    arr[i] = i

In [126]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [127]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [128]:
arr = np.arange(32).reshape((8, 4))

In [129]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [130]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [131]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])