In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
obj = pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])

In [4]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [5]:
new_obj = obj.drop("c")

In [6]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [7]:
obj.drop(["d", "c"])

a    0
b    1
e    4
dtype: int64

In [8]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])

In [9]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [12]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [13]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [14]:
obj["b"]

1.0

In [15]:
obj[1]

1.0

In [16]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [17]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [18]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [19]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [20]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [21]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [22]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [23]:
obj1

2    1
0    2
1    3
dtype: int64

In [24]:
obj2

a    1
b    2
c    3
dtype: int64

In [25]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [26]:
obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [27]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [28]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [29]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [30]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])

In [31]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [34]:
data["one"]

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [35]:
data["three"]

Ohio         2
Colorado     6
Utah        10
New York    14
Name: three, dtype: int64

In [36]:
data["four"]

Ohio         3
Colorado     7
Utah        11
New York    15
Name: four, dtype: int64

In [37]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [39]:
data[data < 5] = 0

In [40]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [42]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [44]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [45]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [46]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [47]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [48]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [49]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [50]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [51]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
ser = pd.Series(np.arange(3.))

In [53]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [54]:
ser[-1]

KeyError: -1

In [55]:
data.loc[:, "one"] = 1

In [56]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [57]:
data.iloc[2] = 5

In [58]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [59]:
data.loc[data["four"] > 5] = 3

In [60]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [66]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [67]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=["a", "c", "e", "f", "g"])

In [68]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [69]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [70]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [71]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                  index=["Ohio", "Texas", "Colorado"])

In [74]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                  index=["Utah", "Ohio", "Texas", "Oregon"])

In [75]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [76]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [77]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [78]:
df1 = pd.DataFrame({"A": [1, 2]})

In [79]:
df2 = pd.DataFrame({"B": [3, 4]})

In [80]:
df1

A
0  1
1  2

In [81]:
df2

B
0  3
1  4

In [82]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [83]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list("abcd"))

In [86]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [87]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list("abcde"))

In [88]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [89]:
df3 = pd.DataFrame(np.arange(20.).reshape((2, 10)),
                  columns=list("abcdefghij"))

In [90]:
df3

a     b     c     d     e     f     g     h     i     j
0   0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
1  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0

In [91]:
df2.loc[1, "b"] = np.nan

In [92]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [93]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [94]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [95]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [96]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [97]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [98]:
arr = np.arange(12.).reshape((3, 4))

In [99]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [100]:
arr1 = np.arange(16.).reshape((4, 4))

In [101]:
arr1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [103]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [104]:
arr[0]

array([0., 1., 2., 3.])

In [105]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [106]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [107]:
series = frame.iloc[0]

In [108]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [109]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [110]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [111]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [112]:
series2

b    0
e    1
f    2
dtype: int64

In [113]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [114]:
series3 = frame["d"]

In [115]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [116]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [117]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [118]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [119]:
frame

b         d         e
Utah    0.831173 -1.507513  0.173407
Ohio    0.889654 -0.177120  0.460874
Texas   1.260295 -0.303294 -1.592066
Oregon  0.915307  1.854184  0.772232

In [120]:
np.abs(frame)

b         d         e
Utah    0.831173  1.507513  0.173407
Ohio    0.889654  0.177120  0.460874
Texas   1.260295  0.303294  1.592066
Oregon  0.915307  1.854184  0.772232

In [122]:
def f1(x):
    return x.max() - x.min()

In [123]:
frame.apply(f1)

b    0.429122
d    3.361696
e    2.364298
dtype: float64